# ========================================
# FileName: silakka.conf
# Brief: configuration file for Silakka ZMK firmware
# Board: nice_nano_v2
# Display: nice_view
# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT
# =========================================

### Keyboard name
# CONFIG_ZMK_KEYBOARD_NAME="Silakka"

### Boost Bluetooth TX power, also make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
# Enables a combination of settings that are planned to be default in future
# versions of ZMK to improve connection stability.
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

### POWER OPTIONS
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
# 15 min (15*60*1000ms)
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# 1 min Idle timeout before entering idle state
# CONFIG_ZMK_IDLE_TIMEOUT=60000

### MOUSE
CONFIG_ZMK_MOUSE=y

### ZMK STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

### OLED/NICE_VIEW DISPLAY
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

### HID for nice!view ePaperDisplay
# Enable eager debouncing to lower input lag
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### Improves compatibility with iPad
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

### TAPPING 
CONFIG_ZMK_MOD_TAP_TAPPING_TERM_MS=280

### DEBUG OPTIONS
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
